"""Inline MingCute SVGs from assets/mc-*.svg into glyphs.css (CSS masks fail on file:// otherwise)."""
import glob
import os
import urllib.parse

HERE = os.path.dirname(os.path.abspath(__file__))
NAMES = {
    "left-line": "back", "right-line": "next", "close-line": "close",
    "lock-fill": "lock", "check-fill": "check", "menu-fill": "menu",
    "filter-2-fill": "filter", "calendar-fill": "cal", "add-fill": "add",
    "star-fill": "star", "more-2-fill": "more", "settings-3-fill": "settings",
    "map-fill": "map", "time-fill": "time",
    "up-fill": "up", "down-fill": "down",
}

lines = ["/* Generated by build_glyphs.py from assets/mc-*.svg (MingCute, Apache-2.0). Do not edit. */"]
for path in sorted(glob.glob(os.path.join(HERE, "assets", "mc-*.svg"))):
    key = os.path.basename(path)[3:-4]
    if key not in NAMES:
        continue
    with open(path, encoding="utf-8") as f:
        svg = f.read().replace("currentColor", "#000")
    lines.append(f'.g-{NAMES[key]} {{ --g: url("data:image/svg+xml,{urllib.parse.quote(svg)}"); }}')

with open(os.path.join(HERE, "glyphs.css"), "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print(f"{len(lines) - 1} glyphs")
